run:
  timeout: 60s

linters:
  # start with everything
  enable-all: true

  disable:
    # deprecated
    - golint
    - interfacer
    - maligned
    - scopelint
    - deadcode
    - varcheck
    - structcheck

    # too annoying
    - cyclop
    - exhaustive
    - exhaustivestruct
    - exhaustruct
    - forbidigo
    - funlen
    - gochecknoglobals
    - godot
    - goerr113
    - gofumpt
    - gomnd
    - lll
    - nakedret
    - nestif
    - nlreturn
    - tagliatelle
    - varnamelen
    - wsl
    - nosnakecase
    - ifshort
    - gci
    - gofmt
    - goimports
    - makezero
    - wrapcheck
    - interfacebloat
    - dupl
    - errorlint
    - gosmopolitan
    - ireturn
    - nolintlint

    # disabled because of generics
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - wastedassign

linters-settings:
  wsl:
    allow-cuddle-declarations: true
